version: '3'
services:
  database:
      image: postgis/postgis:15-3.3-alpine
      container_name: "database-container"
      volumes:
        - ./db-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s  
      env_file:
        - env_file
      restart: always
      networks:
        - custom
  backend:
    build: .
    container_name: "api-container"
    restart: always
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - custom

volumes:
  db-data: {}
  backend_node_modules: {}

secrets:
  db-password:
    file: db/password.txt
    
networks:
  private:

